name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t himansusekhar752/userside --build-arg base_url='http://44.202.140.63:5000/api' .
      - name: Publish Image to docker hub
        run: docker push himansusekhar752/userside:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull himansusekhar752/userside:latest
      - name: Stop and remove previous container if exists
        run: |
          docker stop ecomerce_userside_container || true
          docker rm ecomerce_userside_container || true
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:80 --name ecomerce_userside_container himansusekhar752/userside
