name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t himansusekhar752/userside .
      - name: Publish Image to docker hub
        run: docker push himansusekhar752/userside:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull himansusekhar752/userside:latest
      - name: Stop and remove previous container if exists
        run: |
          docker stop ecomerce_userside_container || true
          docker rm ecomerce_userside_container || true
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name ecomerce_userside_container \
            -e MONGODB_URL='${{ secrets.MONGODB_URL }}' \
            -e PAYMENT_KEY='${{ secrets.PAYMENT_KEY }}' \
            -e PAYMENT_SECRET_KEY='${{ secrets.PAYMENT_SECRET_KEY }}' \
            -e SECRET_KEY='${{ secrets.SECRET_KEY }}' \
            -e API_KEY='${{ secrets.API_KEY }}' \
            -e CLOUD_NAME='${{ secrets.CLOUD_NAME }}' \
            -e MP='${{ secrets.MP }}' \
            -e MAIL_ID='${{ secrets.MAIL_ID }}' \
            -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
            himansusekhar752/userside
